#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
###########- COLOR CODE -##############
colornow=$(cat /etc/anggun/theme/color.conf)
#NC="\e[0m"
#RED="\033[0;31m" 
COLOR1="$(cat /etc/anggun/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/anggun/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')" 
WH='\033[1;37m'                   
###########- Yaddy Kakkoii-##########
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
On_IPurple='\033[0;105m'  #
On_IRed='\033[0;101m'
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White
#NC='\e[0m'
# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'
# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"
# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"
# // Root Checking
if [ "${EUID}" -ne 0 ]; then
		echo -e "${EROR} Please Run This Script As Root User !"
		exit 1
fi
function autokill(){
    Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
    Info="${Green_font_prefix}[ON]${Font_color_suffix}"
    Error="${Red_font_prefix}[OFF]${Font_color_suffix}"
    cek=$(grep -c -E "^# Autokill" /etc/cron.d/tendang)
    if [[ "$cek" = "1" ]]; then
        sts="${Info}"
    else
        sts="${Error}"
    fi
    clear
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;39m             AUTOKILL SSH          \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "Status Autokill : $sts        "
    echo -e ""
    echo -e "[1]  AutoKill After 5 Minutes"
    echo -e "[2]  AutoKill After 10 Minutes"
    echo -e "[3]  AutoKill After 15 Minutes"
    echo -e "[4]  Turn Off AutoKill/MultiLogin"
    echo -e "[x]  Menu"
    echo ""
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e ""
    read -p "Select From Options [1-4 or x] :  " AutoKill
    read -p "Multilogin Maximum Number Of Allowed: " max
    echo -e ""
    case $AutoKill in
        1)
        echo -e ""
        sleep 1
        clear
        echo > /etc/cron.d/tendang
        echo "# Autokill" >/etc/cron.d/tendang
        echo "*/5 * * * *  root /usr/bin/tendang $max" >>/etc/cron.d/tendang && chmod +x /etc/cron.d/tendang
        echo "" > /root/log-limit.txt
        echo -e ""
        echo -e "======================================"
        echo -e ""
        echo -e "      Allowed MultiLogin : $max"
        echo -e "      AutoKill Every     : 5 Minutes"      
        echo -e ""
        echo -e "======================================"
        service cron reload >/dev/null 2>&1
        service cron restart >/dev/null 2>&1                                                                 
        ;;
        2)
        echo -e ""
        sleep 1
        clear
        echo > /etc/cron.d/tendang
        echo "# Autokill" >/etc/cron.d/tendang
        echo "*/10 * * * *  root /usr/bin/tendang $max" >>/etc/cron.d/tendang && chmod +x /etc/cron.d/tendang
        echo "" > /root/log-limit.txt
        echo -e ""
        echo -e "======================================"
        echo -e ""
        echo -e "      Allowed MultiLogin : $max"
        echo -e "      AutoKill Every     : 10 Minutes"
        echo -e ""
        echo -e "======================================"
        service cron reload >/dev/null 2>&1
        service cron restart >/dev/null 2>&1
        ;;
        3)
        echo -e ""
        sleep 1
        clear
        echo > /etc/cron.d/tendang
        echo "# Autokill" >/etc/cron.d/tendang
        echo "*/15 * * * *  root /usr/bin/tendang $max" >>/etc/cron.d/tendang && chmod +x /etc/cron.d/tendang
        echo "" > /root/log-limit.txt
        echo -e ""
        echo -e "======================================"
        echo -e ""
        echo -e "      Allowed MultiLogin : $max"
        echo -e "      AutoKill Every     : 15 Minutes"
        echo -e ""
        echo -e "======================================"
        service cron reload >/dev/null 2>&1
        service cron restart >/dev/null 2>&1          
        ;;
        4)
        rm -fr /etc/cron.d/tendang
        echo "" > /root/log-limit.txt
        echo -e ""
        echo -e "======================================"
        echo -e ""
        echo -e "      AutoKill MultiLogin Turned Off"
        echo -e ""
        echo -e "======================================"
        service cron reload >/dev/null 2>&1
        service cron restart >/dev/null 2>&1
        ;;
        x)
        menu
        ;;
        *)
        echo "Please enter an correct number"
        ;;
    esac
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
}
autokill
