#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
###########- COLOR CODE -##############
#& vless ### vmess #! trojanws ## ssws
colornow=$(cat /etc/anggun/theme/color.conf)
COLOR1="$(cat /etc/anggun/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/anggun/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')" 
WH='\033[1;37m'
NC="\e[0m"
RED="\033[0;31m"
clear
###########- Yaddy Kakkoii-##########
#sshudpserver=$( systemctl status alter-udp-yaddyganteng | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
function menuudp() {
#Script Installer UDP by anggun 
#echo -e "$COLOR1 $NC ${WH}[ SSH UDP : ${status_sshudp} ${WH}] $COLOR1 $NC"
function sockipudpreques(){
    cd
    rm -f /etc/udp
    mkdir -p /etc/udp
    #Decrypted By YADDY D PHREAKER #=== setup ===&>/dev/null
    sudo apt update -y && sudo apt upgrade -y 
    sudo apt install -y wget && sudo apt install -y curl && sudo apt install -y dos2unix
    wget "https://raw.githubusercontent.com/arismaramar/freepremium/main/udp-request" -O /usr/bin/udp-request
    chmod +x /usr/bin/udp-request
    wget -O /bin/udpgw 'https://raw.githubusercontent.com/arismaramar/freepremium/main/udpgw'
    chmod +x /bin/udpgw
    wget -O /etc/systemd/system/udpgw.service 'https://raw.githubusercontent.com/arismaramar/freepremium/main/udpgw.service'
    chmod 777 /etc/systemd/system/udpgw.service
    wget -O /etc/systemd/system/udp-request.service 'https://raw.githubusercontent.com/arismaramar/freepremium/main/udp-request.service'
    chmod 777 /etc/systemd/system/udp-request.service
    wget "https://raw.githubusercontent.com/arismaramar/freepremium/main/sockipconfig.json" -O /etc/udp/config.json
    chmod 777 /etc/udp/config.json
    systemctl daemon-reload
    systemctl enable udpgw && systemctl start udpgw
    systemctl enable udp-request && systemctl start udp-request
    systemctl enable udpgw.service && systemctl start udpgw.service
    systemctl enable udp-request.service && systemctl start udp-request.service
    clear
    echo "==========SCRIPT UDP REQUEST APK SOCKSIP SUKSES TERINSTAL==========="
    sleep 2
    menuudp
}
function stopsockip(){
    systemctl daemon-reload
    systemctl disable udpgw && systemctl stop udpgw
    systemctl disable udp-request && systemctl stop udp-request
    systemctl disable udpgw.service && systemctl stop udpgw.service
    systemctl disable udp-request.service && systemctl stop udp-request.service
    echo "UDP Sockip telah Berhenti... "
    sleep 2
    clear
    menu
}
function startsockip(){
    systemctl daemon-reload
    systemctl enable udpgw && systemctl start udpgw
    systemctl enable udp-request && systemctl start udp-request
    systemctl enable udpgw.service && systemctl start udpgw.service
    systemctl enable udp-request.service && systemctl start udp-request.service
    echo "UDP Sockip Starting... "
    sleep 2
    clear
    menuudp
}
function startsshudp(){
    #systemctl start udp-custom &>/dev/null
    systemctl daemon-reload
    systemctl start udpcore &>/dev/null
    systemctl enable udpcore &>/dev/null
    service udpcore restart
    echo "UDP Http Custom Starting... "
    sleep 2
    clear
    menu
}
function stopsshudp(){
    #systemctl stop alter-udp-yaddyganteng
    systemctl daemon-reload
    systemctl stop udpcore
    echo "UDP Http Custom telah berhenti... "
    sleep 2
    clear
    menu
}
function installsshudp(){
#  ##
    wget -qO installsshudplama "https://raw.githubusercontent.com/arismaramar/freepremium/main/installsshudplama.sh"
    chmod +x installsshudplama && ./installsshudplama 2200,7100,7200,7300,53,5300
    clear
    rm -f installsshudplama
    clear
    echo " "
    echo "==========SCRIPT UDP SUKSES TERINSTAL==========="
    echo " "
    echo "================-anggun-==============" | tee -a log-install.txt
    echo "" | tee -a log-install.txt
    echo "----------------------------------------------" | tee -a log-install.txt
    echo "" | tee -a log-install.txt
    echo "   - Telegram           : t.me/amantubilah" | tee -a log-install.txt
    echo "   - Instagram          : @anggun" | tee -a log-install.txt
    echo "   - Whatsapp           : wa.me/6285365581599" | tee -a log-install.txt
    echo "--------Script Created By anggun ------"      | tee -a log-install.txt
    echo ""
    echo "========SUKSES MENGINSTALL UDP-CUSTOM========"
    echo ""
    rm -f install-udp
    sleep 3
    clear
    menu
}
    #Script Installer UDP by anggun
    udpcustom=$( systemctl status udpcore | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
    if [[ $udpcustom == "running" ]]; then
        status_udpcustom="${COLOR1}ON${NC}"
    else
        status_udpcustom="${RED}OFF${NC}"
    fi
sockipp(){
    udpsockip=$( systemctl status udp-request.service | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
    if [[ $udpsockip == "running" ]]; then
        status_udpsockip="${COLOR1}ON${NC}"
    else
        status_udpsockip="${RED}OFF${NC}"
    fi
}
    echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
    echo -e "$COLOR1 ${NC} ${COLBG1}               ${WH}• SSHUDP PANEL MENU •              ${NC} $COLOR1 $NC"
    echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
    echo -e " $COLOR1┌───────────────────────────────────────────────┐${NC}"
    echo ""
    echo -e "$COLOR1 $NC ${WH}[ SSH UDP HTTPCUSTOM : ${status_udpcustom} ${WH}] $COLOR1 $NC"
#    echo -e "$COLOR1 $NC ${WH}[ SSH UDP APK SOCKSIP : ${status_udpsockip} ${WH}] $COLOR1 $NC"
    echo ""
    echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
    echo -e "\033[0;36m[01]\033[m | START SSH UDP Http Custom"
    echo -e "\033[0;36m[02]\033[m | STOP SSH UDP Http Custom"
    echo -e "\033[0;36m[03]\033[m | START SSH UDP request socksip"
    echo -e "\033[0;36m[04]\033[m | STOP SSH UDP request socksip"
    echo -e "\033[0;36m[05]\033[m | RE INSTALL UDP CORE, APK HTTPCUSTOM "
#    echo -e "\033[0;36m[06]\033[m | RE INSTALL UDP CORE, APK HTTPCUSTOM VERSI LAMA"
    echo -e "\033[0;36m[06]\033[m | RE INSTALL UDP REQUEST, APK SOCKSIP "
    echo -e "\033[0;36m[00]\033[m | Ketik 0 untuk Kembali ke Menu"
    echo -e "\033[0;36m['x]\033[m | Ketik x untuk KELUAR"
    echo ""
    echo -ne "\033[0;36m😁 Silakan Pilih Menu nomer PIRO ?\0033[m "
    echo ""
    echo ""
    read -p "Select From Options : " menu_num
	case $menu_num in
    	1) startsshudp ;;
    	2) stopsshudp ;;
    	3) startsockip ;;
    	4) stopsockip ;;
    	5) installsshudp 2200,7100,7200,7300,53,5300 ;;
    	6) sockipudpreques ;;
        00 | 0) clear ; menu ;;
        X | x) exit ;;
    	*) echo -e "You WRONG COMMAND !"
    	sleep 2 ; clear ; menuudp ;;
    esac
}
menuudp
